# Generated by Django 4.1.5 on 2023-08-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subcategory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=True, max_length=100, unique=True),
        ),
    ]
