# Generated by Django 4.1.5 on 2023-08-16 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory1',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
