# Generated by Django 4.1.5 on 2023-08-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_category_subcategory1_subcategory_category1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category1',
            new_name='category',
        ),
    ]
