# Generated by Django 4.1.5 on 2023-08-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_category1_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory'),
        ),
    ]
